version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports: 
      - "5050:80"
    restart: always
    depends_on:
     - postgres

  backend:
    build: ./backend/.
    command: npm run dev
    ports:
     - 3333:3333
    volumes:
     - ./backend/.:/usr/back
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend/.
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/.:/usr/front
    depends_on:
      - backend

  